// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.NationalDebt
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("totalDebt")]
        public double TotalDebt { get; set; }

        [JsonProperty("totalDebtFormatted")]
        public string TotalDebtFormatted { get; set; }

        [JsonProperty("publicDebt")]
        public double PublicDebt { get; set; }

        [JsonProperty("publicDebtFormatted")]
        public string PublicDebtFormatted { get; set; }

        [JsonProperty("intragovernmentalDebt")]
        public double IntragovernmentalDebt { get; set; }

        [JsonProperty("intragovernmentalDebtFormatted")]
        public string IntragovernmentalDebtFormatted { get; set; }

        [JsonProperty("perCapita")]
        public long PerCapita { get; set; }

        [JsonProperty("perCapitaFormatted")]
        public string PerCapitaFormatted { get; set; }

        [JsonProperty("population")]
        public long Population { get; set; }
    }
}
